Docpic.create!([
  {title: "Example Homework 2", document_file_name: "ExampleHomework_2.docx", document_content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", document_file_size: 4300, document_updated_at: "2017-03-21 22:48:32", subgroup_id: 1, user_id: 1},
  {title: "Example Homework 1 ", document_file_name: "ExampleHomework.docx", document_content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", document_file_size: 4300, document_updated_at: "2017-03-21 15:35:43", subgroup_id: 1, user_id: 1},
  {title: "Homework 3/21/2017", document_file_name: "ExampleHomework_3.docx", document_content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", document_file_size: 4300, document_updated_at: "2017-03-21 23:18:45", subgroup_id: 1, user_id: 5},
  {title: "Homework 3/27/2017", document_file_name: "ExampleHomework_4.docx", document_content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", document_file_size: 4300, document_updated_at: "2017-03-26 17:06:58", subgroup_id: 1, user_id: 5},
  {title: "Cuban Black Beans Recipe", document_file_name: "BlackBeans.pdf", document_content_type: "application/pdf", document_file_size: 48734, document_updated_at: "2017-03-28 00:49:47", subgroup_id: 10, user_id: 4},
  {title: "homework", document_file_name: "ExampleHomework_5.docx", document_content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", document_file_size: 4300, document_updated_at: "2017-03-29 22:26:26", subgroup_id: 3, user_id: 21}
])
Event.create!([
  {group_id: nil, subgroup_id: 10, name: "Learning to Cook beans. ", date: "2017-04-02", description: "Learning how this dynamic legume can be used as a cheap and healthy protein and how it is utilized in different cultures throughout the world. ", registration_deadline: "2017-03-31", due_date: nil, must_register?: true},
  {group_id: nil, subgroup_id: 13, name: "Making a budget and saving.", date: "2017-04-22", description: "TIps for financial organization. ", registration_deadline: "2017-04-19", due_date: nil, must_register?: true},
  {group_id: nil, subgroup_id: 5, name: "Practice #1", date: "2017-04-01", description: "Practice", registration_deadline: "2017-03-31", due_date: nil, must_register?: true},
  {group_id: nil, subgroup_id: 6, name: "Practice #1", date: "2017-04-01", description: "Practice", registration_deadline: nil, due_date: nil, must_register?: true},
  {group_id: nil, subgroup_id: 7, name: "Practice #1", date: "2017-04-01", description: "Practice", registration_deadline: "2017-03-31", due_date: nil, must_register?: true},
  {group_id: nil, subgroup_id: 8, name: "Park clean up. ", date: "2017-04-16", description: "Make the park a better place for kids and families to play. ", registration_deadline: nil, due_date: nil, must_register?: true},
  {group_id: nil, subgroup_id: 9, name: "Math Help Wednesdays", date: "2017-04-05", description: "Bringing math teachers together with kids having a hard time with their current topics. All High School grades and subjects.", registration_deadline: "2017-04-04", due_date: nil, must_register?: true},
  {group_id: nil, subgroup_id: 9, name: "Math Help Wednesdays", date: "2017-04-12", description: "Bringing math teachers together with kids having a hard time with their current topics. All High School grades and subjects.", registration_deadline: "2017-04-11", due_date: nil, must_register?: true},
  {group_id: nil, subgroup_id: 13, name: "Balancing  your checkbook", date: "2017-04-20", description: "Total the expenditures.", registration_deadline: "2017-04-12", due_date: nil, must_register?: true},
  {group_id: nil, subgroup_id: 8, name: "Tree Planter Cleaning", date: "2017-04-08", description: "Get all the tree planters on your block looking better for the spring and summer.", registration_deadline: "2017-04-07", due_date: nil, must_register?: true},
  {group_id: nil, subgroup_id: 1, name: "Office Hours", date: "2017-04-07", description: "Work with your teacher", registration_deadline: nil, due_date: nil, must_register?: true},
  {group_id: nil, subgroup_id: 1, name: "Algebra Quiz 1", date: "2017-03-21", description: "The first quiz for algebra ", registration_deadline: nil, due_date: nil, must_register?: false},
  {group_id: nil, subgroup_id: 4, name: "Lecture", date: "2017-03-22", description: " ser & estar, to be and to be - learning the differences between the two ", registration_deadline: nil, due_date: nil, must_register?: false},
  {group_id: nil, subgroup_id: 4, name: "Homework", date: "2017-03-23", description: "#1 - learn hello goodbye", registration_deadline: nil, due_date: "2017-03-24", must_register?: false},
  {group_id: nil, subgroup_id: 4, name: "Quiz #1", date: "2017-03-30", description: "Animals Vocab", registration_deadline: nil, due_date: nil, must_register?: false},
  {group_id: nil, subgroup_id: 1, name: "Homework 1 ", date: "2017-03-21", description: "Equations", registration_deadline: nil, due_date: "2017-03-22", must_register?: false},
  {group_id: nil, subgroup_id: 1, name: "Lecture 1", date: "2017-03-21", description: "Equations", registration_deadline: nil, due_date: nil, must_register?: false},
  {group_id: nil, subgroup_id: 3, name: "Homework 1 ", date: "2017-03-21", description: "Plant Structure ", registration_deadline: nil, due_date: "2017-03-22", must_register?: false},
  {group_id: nil, subgroup_id: 3, name: "Lecture 1", date: "2017-03-21", description: "Plant Structure ", registration_deadline: nil, due_date: nil, must_register?: false},
  {group_id: nil, subgroup_id: 3, name: "Quiz 1", date: "2017-03-23", description: "Plant Structure ", registration_deadline: nil, due_date: nil, must_register?: false},
  {group_id: nil, subgroup_id: 5, name: "Game vs Team 2 ", date: "2017-04-08", description: "Competition", registration_deadline: nil, due_date: nil, must_register?: false},
  {group_id: nil, subgroup_id: 6, name: "Game vs Team 1", date: "2017-04-08", description: "Competition", registration_deadline: nil, due_date: nil, must_register?: false},
  {group_id: nil, subgroup_id: 5, name: "Game vs Team 3", date: "2017-04-15", description: "Competition", registration_deadline: nil, due_date: nil, must_register?: false},
  {group_id: nil, subgroup_id: 7, name: "Game vs Team 1", date: "2017-04-15", description: "Competition", registration_deadline: nil, due_date: nil, must_register?: false},
  {group_id: nil, subgroup_id: 6, name: "Game vs Team 3", date: "2017-04-22", description: "Competition", registration_deadline: nil, due_date: nil, must_register?: false},
  {group_id: nil, subgroup_id: 7, name: "Game vs Team 2 ", date: "2017-04-22", description: "Competition", registration_deadline: nil, due_date: nil, must_register?: false}
])
Group.create!([
  {name: "volunteer group", description: "this group helps do things", category: "volunteer", email: "groupstogethervolunteer@gmail.com"},
  {name: "school", description: "this is a school that teaches things", category: "education", email: "groupstogetherschool@gmail.com"},
  {name: "sports league", description: "youth sports league with several teams", category: "sports", email: "groupstogethersports@gmail.com"}
])
Message.create!([
  {body: "Hi teacher. I need help", user_id: 5, subgroup_id: 1},
  {body: "How can I help?", user_id: 1, subgroup_id: 1},
  {body: "hello", user_id: 1, subgroup_id: 1},
  {body: "I can't add", user_id: 5, subgroup_id: 1},
  {body: "hello", user_id: 5, subgroup_id: 1},
  {body: "hi", user_id: 1, subgroup_id: 1},
  {body: "como de dice hello en espanol?", user_id: 5, subgroup_id: 4},
  {body: "hola", user_id: 1, subgroup_id: 4},
  {body: "hi everyone", user_id: 1, subgroup_id: 3},
  {body: "lets chat", user_id: 1, subgroup_id: 3},
  {body: "can you help me learn science?", user_id: 9, subgroup_id: 3},
  {body: "hey!", user_id: 1, subgroup_id: 1},
  {body: "hey guys your homework is due tomorrow", user_id: 1, subgroup_id: 1},
  {body: "Is this working?", user_id: 21, subgroup_id: 10},
  {body: "this is the most recent comment", user_id: 1, subgroup_id: 1},
  {body: "do I like this when it loads from the top?", user_id: 1, subgroup_id: 1},
  {body: "Hi guys. I am happy to teach your class!", user_id: 26, subgroup_id: 1},
  {body: "Looking forward to seeing you all tomorrow.", user_id: 26, subgroup_id: 1},
  {body: "hi", user_id: 27, subgroup_id: 3},
  {body: "not really", user_id: 27, subgroup_id: 3},
  {body: "test", user_id: 1, subgroup_id: 1},
  {body: "Hello!", user_id: 21, subgroup_id: 3},
  {body: "can i get some help", user_id: 21, subgroup_id: 3},
  {body: "hello", user_id: 4, subgroup_id: 8},
  {body: "ggg", user_id: 1, subgroup_id: 1},
  {body: "hhhh", user_id: 21, subgroup_id: 1},
  {body: "hello", user_id: 21, subgroup_id: 1},
  {body: "did you do your homework?", user_id: 1, subgroup_id: 1}
])
Subgroup.create!([
  {group_id: 1, name: "Math", description: "beginner stuff"},
  {group_id: 1, name: "Science", description: "Biology 1 "},
  {group_id: 1, name: "Spanish 1 ", description: "Intro to Spanish "},
  {group_id: 2, name: "Team 1 ", description: "Schedule and participants for Team 1."},
  {group_id: 2, name: "Team 2 ", description: "Schedule and participants for Team 2."},
  {group_id: 2, name: "Team 3 ", description: "Schedule and participants for Team 3."},
  {group_id: 3, name: "Neighborhood Beautification", description: "Events and Participants for keeping the hood looking good. "},
  {group_id: 3, name: "After School Homework Helpers", description: "Assisting kids in the neighborhood with their homework."},
  {group_id: 3, name: "Healthy and Affordable Cooking classes", description: "Free instruction on how to cook cheap healthy food for the whole family. "},
  {group_id: 3, name: "Personal Finance Class", description: "Helps people get their financial lives in order. "}
])
User.create!([
  {first_name: "Juan", last_name: "Mata", email: "jm@email.com", password_digest: "$2a$10$j7JIMs5zdRs3Rv/.SiXHnOAPByLlURYL1fuGMaA1zzcyGdRDI2R7C"},
  {first_name: "Suzzy", last_name: "Howard", email: "sh@email.com", password_digest: "$2a$10$TQq.yEGET6LGfAkYKf4Unet41nNoKN2MOcIDNAw/ydbEPMJZTsBwa"},
  {first_name: "Happy", last_name: "Day", email: "hd@email.com", password_digest: "$2a$10$WoesKfDpTp6acIDfsAKU1.z9NzD6hc.SOrZA8/vCAmbrjGn1GP2mK"},
  {first_name: "Some", last_name: "Day", email: "sd@email.com", password_digest: "$2a$10$ss7g2HoegusjzZY.jd5YqeF72huEjK1amEHUtv.tzbIOdxh60Ww62"},
  {first_name: "Another", last_name: "Day", email: "ad@email.com", password_digest: "$2a$10$jlA9CvKR0poLx3NrP1HRZ.X4TjoUIoNnajMtCyT/8b4XD18lFRwXS"},
  {first_name: "Fantastic", last_name: "Day", email: "fd@email.com", password_digest: "$2a$10$3kBSLr.ZMs3QXE35jx.Pweg/JDlwY9yjb3L0pk77nn.QYAlyj23gS"},
  {first_name: "James", last_name: "Samson", email: "js@email.com", password_digest: "$2a$10$tkK6L8JFwo/SBI2/Cbxb4uTDwDCRYZWpyft3gogx75xoaBf0h.OHq"},
  {first_name: "Jamie", last_name: "Hansen", email: "jamiehansen@email.com", password_digest: "$2a$10$jAASPQhKr/7XlNugFNXA7upr/GyMGzKUCv.iEFahlX5rRkJP9rxNC"},
  {first_name: "Zak", last_name: "Woods", email: "zakwoods@email.com", password_digest: "$2a$10$LAV5ObjOW0ILEzNDJ.fI0eOArl24vA6VSqlXEH/.s9DTmZElUE/wm"},
  {first_name: "Will", last_name: "Brown", email: "willbrown@email.com", password_digest: "$2a$10$ZWoZy6vr38228ufBcR67h.wAykLG0waGFZoOynesJ03GyQtdo2vb."},
  {first_name: "John", last_name: "Doe", email: "groupstogetherschool@gmail.com", password_digest: "$2a$10$JQgFjrW3llDCNebv222UfOd9HuntsleWKDtdX5khXsStDpj6g.cOu"},
  {first_name: "Bill", last_name: "Smith", email: "groupstogethersports@gmail.com", password_digest: "$2a$10$oOndBPsUrajsQCMdP7/5RuRCZKg.u0BhMKt4fgfYp9ymnXLoU4uCm"},
  {first_name: "Peter", last_name: "Strong", email: "peter.strong@gmail.com", password_digest: "$2a$10$heEQPNGgA6f.m7HyBs.YbOoSlCyvRRzQO5116kI9JYikU2Vre3zE2"},
  {first_name: "Bill", last_name: "Bob", email: "billybob@email.com", password_digest: "$2a$10$SXsrUytyHS841D2umBWpKuzmp/KIovKvNBA10Fw3/.39OO.H8ddYm"},
  {first_name: "andy", last_name: "z", email: "az@ex.com", password_digest: "$2a$10$xVWwmBU.XJTBnq/vUOtoi.Ys7KGBiUR2IvFQoVTZSUIp1WVCeUOji"},
  {first_name: "Mike", last_name: "Yatco", email: "my@email.com", password_digest: "$2a$10$ibCpxeOdERR4gHEmsED6neElb5.lQ/uPYdUDLk5KtRYJkcrFnQNZa"},
  {first_name: "Jimmy", last_name: "Johnson", email: "jimmyjohnson@email.com", password_digest: "$2a$10$7z8JRWDmAsy5PSMoFN4xmucocffhue3q0Qe1VdpamD9gpXyEM3bKe"},
  {first_name: "Chris", last_name: "Hemingway", email: "chrish@email.com", password_digest: "$2a$10$Kt30JVx4E31EtJNZKGVJRuI/BzZwrzuYGb9qjKMFGSf3P1PLFia/i"},
  {first_name: "Frank", last_name: "Rizzo", email: "frankrizzo@email.com", password_digest: "$2a$10$brSOIh7pXK9PPtGQdXak6e67Hysm87gYgYR5RjSTBvj7Q.T8Iv7Y6"},
  {first_name: "Arthur", last_name: "Williams", email: "arthurwilliams@email.com", password_digest: "$2a$10$4sGu36cfOU6N2HrFD5yAdurSNimaYppLbjAVX8A.xovnVNh87ZXfu"},
  {first_name: "Billy", last_name: "Bob", email: "bb@email.com", password_digest: "$2a$10$B991flWoOcuAowqlsIegm.5PcwjtUAPri5juO3bJbOJXLPLicnGVe"},
  {first_name: "Henry", last_name: "Walsh", email: "henrywalsh@email.com", password_digest: "$2a$10$rmUlbw16i4jFUDsTFe/8IOVlc.HCDG7v75keZYROyNmqiZiEEiE3K"},
  {first_name: "Greg", last_name: "Smith", email: "gregsmith@email.com", password_digest: "$2a$10$qUlNbYSKMOoFemMxtE.UFevA4DIuuwj8jywEz1lg4Me9UTzNaeAtm"},
  {first_name: "Lynn", last_name: "Strong", email: "lynnstegerstrong@gmail.com", password_digest: "$2a$10$30MMxCQJzRrvWzcHe2N34OXuVR3FgeYBexKTq0ok5Y513yjFTJAk6"},
  {first_name: "Henry", last_name: "Williams", email: "groupstogethervolunteer@gmail.com", password_digest: "$2a$10$8A0wxHshnaPFraD1cFUEfutbt4OPsPf9xFsSKSsdRAmFNyUVgWctS"},
  {first_name: "user", last_name: "another user", email: "useremail@email.com", password_digest: "$2a$10$w7PQyXrE9jeL3WMknlITOOFpYnBTJiGWpDtwwZHZKVGI7ZLTAEITe"}
])
UserEvent.create!([
  {user_id: 3, event_id: 13, registered: nil},
  {user_id: 3, event_id: 14, registered: nil},
  {user_id: 3, event_id: 16, registered: nil},
  {user_id: 3, event_id: 17, registered: nil},
  {user_id: 3, event_id: 18, registered: nil},
  {user_id: 3, event_id: 19, registered: nil},
  {user_id: 3, event_id: 20, registered: nil},
  {user_id: 8, event_id: 21, registered: nil},
  {user_id: 16, event_id: 21, registered: nil},
  {user_id: 8, event_id: 22, registered: nil},
  {user_id: 16, event_id: 22, registered: nil},
  {user_id: 4, event_id: 22, registered: nil},
  {user_id: 8, event_id: 23, registered: nil},
  {user_id: 16, event_id: 23, registered: nil},
  {user_id: 16, event_id: 24, registered: nil},
  {user_id: 8, event_id: 25, registered: nil},
  {user_id: 16, event_id: 25, registered: nil},
  {user_id: 1, event_id: 1, registered: false},
  {user_id: 1, event_id: 3, registered: true},
  {user_id: 1, event_id: 10, registered: false},
  {user_id: 1, event_id: 5, registered: true},
  {user_id: 1, event_id: 4, registered: true},
  {user_id: 5, event_id: 9, registered: nil},
  {user_id: 1, event_id: 6, registered: true},
  {user_id: 9, event_id: 3, registered: nil},
  {user_id: 5, event_id: 3, registered: nil},
  {user_id: 8, event_id: 26, registered: nil},
  {user_id: 16, event_id: 26, registered: nil},
  {user_id: 4, event_id: 26, registered: nil},
  {user_id: 32, event_id: 26, registered: nil},
  {user_id: 32, event_id: 25, registered: nil},
  {user_id: 3, event_id: 1, registered: false},
  {user_id: 1, event_id: 7, registered: false},
  {user_id: 1, event_id: 8, registered: false},
  {user_id: 1, event_id: 9, registered: false},
  {user_id: 1, event_id: 11, registered: false},
  {user_id: 4, event_id: 21, registered: true},
  {user_id: 4, event_id: 25, registered: true},
  {user_id: 4, event_id: 23, registered: true},
  {user_id: 31, event_id: 21, registered: false},
  {user_id: 8, event_id: 27, registered: nil},
  {user_id: 16, event_id: 27, registered: nil},
  {user_id: 31, event_id: 27, registered: nil},
  {user_id: 4, event_id: 27, registered: nil},
  {user_id: 10, event_id: 15, registered: nil},
  {user_id: 10, event_id: 16, registered: nil},
  {user_id: 10, event_id: 17, registered: nil},
  {user_id: 9, event_id: 9, registered: nil},
  {user_id: 3, event_id: 12, registered: true},
  {user_id: 3, event_id: 15, registered: true},
  {user_id: 21, event_id: 13, registered: nil},
  {user_id: 21, event_id: 12, registered: true},
  {user_id: 8, event_id: 24, registered: true},
  {user_id: 5, event_id: 28, registered: nil},
  {user_id: 9, event_id: 28, registered: nil},
  {user_id: 1, event_id: 28, registered: nil},
  {user_id: 26, event_id: 28, registered: nil},
  {user_id: 21, event_id: 21, registered: true},
  {user_id: 21, event_id: 3, registered: nil},
  {user_id: 21, event_id: 27, registered: true},
  {user_id: 9, event_id: 7, registered: nil},
  {user_id: 21, event_id: 28, registered: false},
  {user_id: 4, event_id: 24, registered: true}
])
UserGroup.create!([
  {user_id: 1, group_id: 1, role: "admin"},
  {user_id: 3, group_id: 2, role: "admin"},
  {user_id: 4, group_id: 3, role: "admin"},
  {user_id: 5, group_id: 1, role: "member"},
  {user_id: 8, group_id: 3, role: "member"},
  {user_id: 6, group_id: 2, role: "member"},
  {user_id: 9, group_id: 1, role: "member"},
  {user_id: 10, group_id: 2, role: "member"},
  {user_id: 16, group_id: 3, role: "member"},
  {user_id: 17, group_id: 2, role: "member"},
  {user_id: 18, group_id: 2, role: "member"},
  {user_id: 19, group_id: 2, role: "member"},
  {user_id: 20, group_id: 2, role: "member"},
  {user_id: 21, group_id: 1, role: "member"},
  {user_id: 21, group_id: 2, role: "member"},
  {user_id: 21, group_id: 3, role: "member"},
  {user_id: 25, group_id: 2, role: "member"},
  {user_id: 26, group_id: 1, role: "editor"},
  {user_id: 27, group_id: 1, role: "editor"},
  {user_id: 24, group_id: 1, role: "editor"},
  {user_id: 28, group_id: 2, role: "editor"},
  {user_id: 29, group_id: 2, role: "editor"},
  {user_id: 30, group_id: 2, role: "editor"},
  {user_id: 31, group_id: 3, role: "editor"},
  {user_id: 32, group_id: 3, role: "editor"},
  {user_id: 33, group_id: 1, role: "member"}
])
UserSubgroup.create!([
  {user_id: 1, subgroup_id: 1},
  {user_id: 3, subgroup_id: 5},
  {user_id: 1, subgroup_id: 3},
  {user_id: 4, subgroup_id: 9},
  {user_id: 3, subgroup_id: 6},
  {user_id: 1, subgroup_id: 4},
  {user_id: 3, subgroup_id: 7},
  {user_id: 4, subgroup_id: 10},
  {user_id: 4, subgroup_id: 8},
  {user_id: 4, subgroup_id: 13},
  {user_id: 5, subgroup_id: 1},
  {user_id: 9, subgroup_id: 1},
  {user_id: 5, subgroup_id: 3},
  {user_id: 9, subgroup_id: 3},
  {user_id: 5, subgroup_id: 4},
  {user_id: 9, subgroup_id: 4},
  {user_id: 17, subgroup_id: 5},
  {user_id: 19, subgroup_id: 5},
  {user_id: 18, subgroup_id: 6},
  {user_id: 10, subgroup_id: 6},
  {user_id: 20, subgroup_id: 7},
  {user_id: 6, subgroup_id: 7},
  {user_id: 8, subgroup_id: 8},
  {user_id: 16, subgroup_id: 8},
  {user_id: 16, subgroup_id: 9},
  {user_id: 8, subgroup_id: 9},
  {user_id: 16, subgroup_id: 10},
  {user_id: 8, subgroup_id: 10},
  {user_id: 8, subgroup_id: 13},
  {user_id: 16, subgroup_id: 13},
  {user_id: 21, subgroup_id: 4},
  {user_id: 21, subgroup_id: 1},
  {user_id: 26, subgroup_id: 1},
  {user_id: 21, subgroup_id: 8},
  {user_id: 21, subgroup_id: 9},
  {user_id: 21, subgroup_id: 10},
  {user_id: 28, subgroup_id: 5},
  {user_id: 31, subgroup_id: 8},
  {user_id: 32, subgroup_id: 9},
  {user_id: 31, subgroup_id: 10},
  {user_id: 32, subgroup_id: 13},
  {user_id: 24, subgroup_id: 4},
  {user_id: 27, subgroup_id: 3},
  {user_id: 21, subgroup_id: 3},
  {user_id: 29, subgroup_id: 7},
  {user_id: 30, subgroup_id: 6},
  {user_id: 21, subgroup_id: 5}
])
